
	
	<!-- start of content and bounding box -->
<div class="box-round">

<tr>
<td width="23" background="/images/bond_box_left_edge.gif"><img src="/images/spacer.gif" width="23" height="1"></td>
<td>

<table border="0" cellspacing="0" cellpadding="4">
<tr>
<td class="error">Insufficient Security Privilege to Search Students.</td>
</tr>
<tr>
<td>Click your browsers "Back" button to return to the previous screen.</td>
</tr>
</table>
</div>
<!-- end of content of bounding box -->

